#!/bin/bash

# RustDesk 一键部署脚本 - 通用常量配置
# Author: RustDesk Team
# Version: 1.0.0

# 脚本版本
SCRIPT_VERSION="1.0.0"

# 项目配置
PROJECT_NAME="RustDesk"
PROJECT_HOME="${PROJECT_HOME:-/opt/rustdesk}"
DATA_DIR="${DATA_DIR:-$PROJECT_HOME/data}"
LOG_DIR="${LOG_DIR:-$PROJECT_HOME/logs}"
CONFIG_DIR="${CONFIG_DIR:-$PROJECT_HOME/config}"
BACKUP_DIR="${BACKUP_DIR:-$PROJECT_HOME/backups}"

# RustDesk 服务端口
HBBDS_PORT="${HBBDS_PORT:-21115}"
HBBDS_TLS_PORT="${HBBDS_TLS_PORT:-21116}"
RELAY_PORT="${RELAY_PORT:-21117}"
NAT_TYPE_TEST_PORT="${NAT_TYPE_TEST_PORT:-21118}"
STATUS_PORT="${STATUS_PORT:-21119}"

# Docker 配置
DOCKER_IMAGE="${DOCKER_IMAGE:-rustdesk/rustdesk-server}"
DOCKER_COMPOSE_FILE="${DOCKER_COMPOSE_FILE:-docker-compose.yml}"
DOCKER_NETWORK="${DOCKER_NETWORK:-rustdesk-net}"

# Kubernetes 配置
K8S_NAMESPACE="${K8S_NAMESPACE:-rustdesk}"
K8S_DEPLOYMENT_NAME="${K8S_DEPLOYMENT_NAME:-rustdesk-server}"
K8S_SERVICE_NAME="${K8S_SERVICE_NAME:-rustdesk}"
K8S_HELM_CHART="${K8S_HELM_CHART:-rustdesk/rustdesk}"

# Redis 配置
REDIS_HOST="${REDIS_HOST:-localhost}"
REDIS_PORT="${REDIS_PORT:-6379}"
REDIS_PASSWORD="${REDIS_PASSWORD:-}"

# PostgreSQL 配置
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_DB="${POSTGRES_DB:-rustdesk}"
POSTGRES_USER="${POSTGRES_USER:-rustdesk}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"

# 安全配置
ENABLE_TLS="${ENABLE_TLS:-true}"
ENABLE_AUTH="${ENABLE_AUTH:-true}"
ENCRYPTION_METHOD="${ENCRYPTION_METHOD:-aes-256-gcm}"

# 日志配置
LOG_LEVEL="${LOG_LEVEL:-info}"
LOG_MAX_SIZE="${LOG_MAX_SIZE:-100M}"
LOG_MAX_AGE="${LOG_MAX_AGE:-30}"
LOG_MAX_BACKUPS="${LOG_MAX_BACKUPS:-7}"

# 备份配置
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-30}"
BACKUP_ENCRYPTION="${BACKUP_ENCRYPTION:-true}"
BACKUP_COMPRESSION="${BACKUP_COMPRESSION:-gzip}"
REMOTE_BACKUP_ENABLED="${REMOTE_BACKUP_ENABLED:-false}"
REMOTE_BACKUP_URL="${REMOTE_BACKUP_URL:-}"

# 性能配置
MAX_CONNECTIONS="${MAX_CONNECTIONS:-1000}"
WORKER_THREADS="${WORKER_THREADS:-4}"
MEMORY_LIMIT="${MEMORY_LIMIT:-2G}"
CPU_LIMIT="${CPU_LIMIT:-2}"

# 超时配置 (秒)
CONNECTION_TIMEOUT="${CONNECTION_TIMEOUT:-30}"
HEALTH_CHECK_INTERVAL="${HEALTH_CHECK_INTERVAL:-60}"
STARTUP_TIMEOUT="${STARTUP_TIMEOUT:-300}"

# 镜像源配置 (中国镜像)
DOCKER_MIRROR="${DOCKER_MIRROR:-https://mirror.ccs.tencentyun.com}"
CARGO_MIRROR="${CARGO_MIRROR:-https://rsproxy.cn}"
GITHUB_MIRROR="${GITHUB_MIRROR:-https://mirror.ghproxy.com}"

# 通知配置
ENABLE_NOTIFICATIONS="${ENABLE_NOTIFICATIONS:-false}"
NOTIFICATION_WEBHOOK="${NOTIFICATION_WEBHOOK:-}"
EMAIL_ALERT="${EMAIL_ALERT:-}"

# 健康检查配置
HEALTH_CHECK_ENABLED="${HEALTH_CHECK_ENABLED:-true}"
HEALTH_CHECK_PORT="${HEALTH_CHECK_PORT:-21120}"

# 监控配置
ENABLE_METRICS="${ENABLE_METRICS:-false}"
METRICS_PORT="${METRICS_PORT:-9090}"
PROMETHEUS_ENABLED="${PROMETHEUS_ENABLED:-false}"
GRAFANA_ENABLED="${GRAFANA_ENABLED:-false}"

# 系统要求
MIN_CPU_CORES="${MIN_CPU_CORES:-2}"
MIN_MEMORY_GB="${MIN_MEMORY_GB:-2}"
MIN_DISK_SPACE_GB="${MIN_DISK_SPACE_GB:-10}"
REQUIRED_PORTS=(21115 21116 21117 21118 21119)

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m'

# 日志标记
INFO="${GREEN}[INFO]${NC}"
WARN="${YELLOW}[WARN]${NC}"
ERROR="${RED}[ERROR]${NC}"
SUCCESS="${GREEN}[SUCCESS]${NC}"
DEBUG="${BLUE}[DEBUG]${NC}"

# 时间格式
TIMESTAMP_FORMAT="${TIMESTAMP_FORMAT:-%Y-%m-%d %H:%M:%S}"

# 国际化
LANG="${LANG:-en}"
if [ "$LANG" = "zh" ] || [ "$LANG" = "zh_CN" ]; then
    MSG_INSTALLED="已安装"
    MSG_NOT_INSTALLED="未安装"
    MSG_RUNNING="运行中"
    MSG_STOPPED="已停止"
    MSG_CHECKING="检查中..."
    MSG_SUCCESS="成功"
    MSG_FAILED="失败"
    MSG_CONTINUE="是否继续?"
    MSG_SELECT_OPTION="请选择选项"
    MSG_INVALID_INPUT="无效输入"
    MSG_OPERATION_CANCELLED="操作已取消"
    MSG_BACKUP_CREATED="备份已创建"
    MSG_RESTORE_COMPLETE="恢复完成"
    MSG_UPDATE_AVAILABLE="有可用更新"
else
    MSG_INSTALLED="Installed"
    MSG_NOT_INSTALLED="Not Installed"
    MSG_RUNNING="Running"
    MSG_STOPPED="Stopped"
    MSG_CHECKING="Checking..."
    MSG_SUCCESS="Success"
    MSG_FAILED="Failed"
    MSG_CONTINUE="Continue?"
    MSG_SELECT_OPTION="Select option"
    MSG_INVALID_INPUT="Invalid input"
    MSG_OPERATION_CANCELLED="Operation cancelled"
    MSG_BACKUP_CREATED="Backup created"
    MSG_RESTORE_COMPLETE="Restore complete"
    MSG_UPDATE_AVAILABLE="Update available"
fi

# 导出所有常量
export SCRIPT_VERSION PROJECT_NAME PROJECT_HOME DATA_DIR LOG_DIR CONFIG_DIR BACKUP_DIR
export HBBDS_PORT HBBDS_TLS_PORT RELAY_PORT NAT_TYPE_TEST_PORT STATUS_PORT
export DOCKER_IMAGE DOCKER_COMPOSE_FILE DOCKER_NETWORK
export K8S_NAMESPACE K8S_DEPLOYMENT_NAME K8S_SERVICE_NAME K8S_HELM_CHART
export REDIS_HOST REDIS_PORT REDIS_PASSWORD
export POSTGRES_HOST POSTGRES_PORT POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD
export ENABLE_TLS ENABLE_AUTH ENCRYPTION_METHOD
export LOG_LEVEL LOG_MAX_SIZE LOG_MAX_AGE LOG_MAX_BACKUPS
export BACKUP_RETENTION_DAYS BACKUP_ENCRYPTION BACKUP_COMPRESSION
export REMOTE_BACKUP_ENABLED REMOTE_BACKUP_URL
export MAX_CONNECTIONS WORKER_THREADS MEMORY_LIMIT CPU_LIMIT
export CONNECTION_TIMEOUT HEALTH_CHECK_INTERVAL STARTUP_TIMEOUT
export DOCKER_MIRROR CARGO_MIRROR GITHUB_MIRROR
export ENABLE_NOTIFICATIONS NOTIFICATION_WEBHOOK EMAIL_ALERT
export HEALTH_CHECK_ENABLED HEALTH_CHECK_PORT
export ENABLE_METRICS METRICS_PORT PROMETHEUS_ENABLED GRAFANA_ENABLED
export MIN_CPU_CORES MIN_MEMORY_GB MIN_DISK_SPACE_GB
