apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbs
  namespace: rustdesk
  labels:
    app: rustdesk-hbbs
    app.kubernetes.io/name: rustdesk
    app.kubernetes.io/component: hbbs
    app.kubernetes.io/part-of: rustdesk-server
spec:
  type: ClusterIP
  ports:
    - name: hbbs-tcp
      port: 21115
      targetPort: 21115
      protocol: TCP
    - name: hbbs-udp
      port: 21116
      targetPort: 21116
      protocol: UDP
  selector:
    app: rustdesk-hbbs
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbs-headless
  namespace: rustdesk
  labels:
    app: rustdesk-hbbs
    app.kubernetes.io/name: rustdesk
    app.kubernetes.io/component: hbbs
    app.kubernetes.io/part-of: rustdesk-server
spec:
  clusterIP: None
  ports:
    - name: hbbs-tcp
      port: 21115
      targetPort: 21115
      protocol: TCP
    - name: hbbs-udp
      port: 21116
      targetPort: 21116
      protocol: UDP
  selector:
    app: rustdesk-hbbs
