{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "rustdesk-server.namespace" . }}
  labels:
    {{- include "rustdesk-server.labels" . | nindent 4 }}
{{- end }}
